"""initial schema

Revision ID: e7bc3d63bde5
Revises:
Create Date: 2026-05-04 14:23:55.935364

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e7bc3d63bde5"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "employees",
        sa.Column("employee_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(), nullable=False),
        sa.Column("last_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("employee_id"),
    )
    op.create_table(
        "food_items",
        sa.Column("food_item_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("food_item_id"),
    )
    op.create_table(
        "tables",
        sa.Column("table_id", sa.Integer(), nullable=False),
        sa.Column("capacity", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("assigned_waiter_id", sa.Integer(), nullable=True),
        sa.Column("current_party_size", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["assigned_waiter_id"],
            ["employees.employee_id"],
        ),
        sa.PrimaryKeyConstraint("table_id"),
    )
    op.create_table(
        "parties",
        sa.Column("party_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("party_size", sa.Integer(), nullable=False),
        sa.Column("table_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["tables.table_id"],
        ),
        sa.PrimaryKeyConstraint("party_id"),
    )
    op.create_table(
        "reservations",
        sa.Column("reservation_id", sa.Integer(), nullable=False),
        sa.Column("customer_name", sa.String(), nullable=False),
        sa.Column("party_size", sa.Integer(), nullable=False),
        sa.Column("table_id", sa.Integer(), nullable=False),
        sa.Column("reservation_time", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["table_id"],
            ["tables.table_id"],
        ),
        sa.PrimaryKeyConstraint("reservation_id"),
    )
    op.create_table(
        "tabs",
        sa.Column("tab_id", sa.Integer(), nullable=False),
        sa.Column("party_id", sa.Integer(), nullable=False),
        sa.Column("total_price", sa.Float(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["party_id"],
            ["parties.party_id"],
        ),
        sa.PrimaryKeyConstraint("tab_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("tabs")
    op.drop_table("reservations")
    op.drop_table("parties")
    op.drop_table("tables")
    op.drop_table("food_items")
    op.drop_table("employees")
    # ### end Alembic commands ###
